---
language: python

services:
  - docker

python:
  - "3.6"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pristine-tar devscripts

   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

  - "pip install -r dev_requirements.txt"

script:
  - flake8
  - python $(which nosetests) -v tests/doctests/ tests/component/deb/ --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_git-buildpackage_2ca3e379bf_0
  - python -m properform Push 47.88.50.110:15554 asdf_git-buildpackage_2ca3e379bf_0 ./profile_git-buildpackage_2ca3e379bf_0


  - tests/helpers/run-in-docker
 #2017-09-12 11:40:07 modified at 0